const zodiacData = [
  {
    id: 1,
    name: "Qoç",
    startDate: [3, 21],
    endDate: [4, 19],
    element: "Atəş",
    planet: "Mars",
    positive: "Cəsarətli, Inamlı, Qərarlı",
    negative: "Təcavüzkar, Səbirsiz, Hövsələsiz",
    compatibility: "Şir, Oxatan",
    love: "Romantik münasibətlərdə ehtiraslı, amma bəzən dominant ola bilər.",
    career: "Liderlik tələb edən sahələrdə uğurlu: idarəetmə, satış, idman.",
    icon: "♈",
    image: "https://freesvg.org/storage/img/thumb/GoldenAries.png",
    description:"Bürclər üç fərqli keyfiyyətə görə qruplaşdırılır: Kardinal (pioner), dəyişkən və sabit bürclər. Qoç dörd əsas bürcdən biridir. Bu bürclər mövsümləri başlayır. Qoç, yazı; Xərçəng, yayı; Tərəzi, payız; Oğlaq qışı başlayır. Bu bürclər orijinal olmağı sevir və etdikləri hər şeydə birinci olmaq istəyirlər. Onlar cari təyinedicilərdir; dostlar çevrəsində partiyaları, təşkilatları başlatanlar onlardır.Bürclərin ilk bürcü olan qoçun varlığı həmişə enerjili və təlatümlü başlanğıcdan xəbər verir. Qoç bürcü həm iş mühitində, həm də dostluq mühitində daim hərəkət, sürət və rəqabətin arxasındadır; Onlar hər şeydə birinci olmağa çalışırlar. Qoç ən aktiv bürclərdən biridir, çünki onların idarə edən planeti Mars od elementinə aiddir. Zaman-zaman düşünmədən belə hərəkət etmək onların təbiətində var."

  },
  {
    id: 2,
    name: "Buğa",
    startDate: [4, 20],
    endDate: [5, 20],
    element: "Torpaq",
    planet: "Venera",
    positive: "Sədaqətli, Praktik, Əzmkar",
    negative: "Maddi yönümlü, Inadkar",
    compatibility: "Oğlaq, Qız",
    love: "Hisslərinə dərin bağlılıq göstərir. Uzunmüddətli münasibətlərə üstünlük verir.",
    career: "Maliyyə, əmlak, kulinariya sahəsində uğurlu.",
    icon: "♉",
    image: "https://freesvg.org/storage/img/thumb/GoldenTaurus.png",
    description:"Bürclər üç fərqli keyfiyyətə görə qruplaşdırılır: kardinal (pioner), dəyişkən və sabit bürclər. Buğa dörd sabit bürcdən biridir; Digər dörd sabit bürc Şir, Əqrəb və Dolçadır. Bu bürclər hər mövsümün ortasına düşür. Bunlar tarazlıq əlamətləridir; Onlar özlərinə məqsəd qoyurlar və sonra tikintiyə başlayırlar. Onlar pioner işarələrinin irəli atdığı maraqlı ideyaları götürür və onları hiss olunan bir şeyə çevirir.Buğa, yer elementi altında qruplaşdırılmış üç bürcdən biridir (digərləri Qız və Oğlaqdır). Bürc dövrünün ilk yer işarəsi olduğu üçün binanı meydana gətirən təməl kimidir. Buğa bürcünün əksəriyyəti balanslaşdırıcıdır, özlərinin və başqalarının təhlükəsizliyini qorumağa çalışır. Onlar hər şeyi sadə, praktik və real perspektivdən görməyə meyllidirlər. Buğa bürcü üçün pul qazanmaq asandır və onlar illərlə eyni layihə üzərində işləyə bilərlər. "
  },
  {
    id: 3,
    name: "Əkizlər",
    startDate: [5, 21],
    endDate: [6, 20],
    element: "Hava",
    planet: "Merkuri",
    positive: "Hazırcavab, Çoxşaxəli, Ünsiyyətcil",
    negative: "Dayanıqsız, Əsəbi, Qərarsız",
    compatibility: "Tərəzi, Dolça",
    love: "Fərqlilik və yenilik istəyir. Partnyorunun intellektual tərəfləri onun üçün önəmlidir.",
    career: "Jurnalistika, təlimçilik, turizm.",
    icon: "♊",
    image: "https://freesvg.org/storage/img/thumb/GoldenGemini.png",
    description:"Bürclər üç fərqli keyfiyyətə görə qruplaşdırılır: kardinal (pioner), dəyişkən və sabit bürclər. Əkizlər dörd dəyişkən bürcdən biridir (digərləri Qız, Oxatan və Balıqlar). Dəyişən əlamətlər fəsilləri bitirən əlamətlərdir və onlar hər fəsildən dərs almışlar. Onlar bilirlər ki, hər şeyin sonu var və onların işi hamının fəsil dəyişikliyinə uyğunlaşmasına kömək etməkdir. Onlar digər bürclərdən daha müdrikdirlər. Onlar digər bürclərə nisbətən dəyişməyə daha asan uyğunlaşa bilirlər; bir çox vəziyyətə uyğunlaşmaq üçün buqələmun kimi rəngini dəyişirlər. Onlar həm də Bürcün düzəldiciləridir: Kardinallar plan irəli sürür, sabit işarələr planı hərəkətə gətirir, dəyişkən əlamətlər isə tənqidi baxışla son nöqtələri qoyur.Əkizlər bürcün hava elementinə sahib olan ilk bürc olduğundan, Əkizlər dəyişiklik və ünsiyyət küləklərini başlatan ilk külək kimidir. Əkizlər əla və yaradıcı sinerji yaradaraq insanları dərhal birləşdirir. Əkizlər planetar dövrədə olanda hamımız dostlarımızla daha çox vaxt keçirməyə meylli oluruq."
  },
  {
    id: 4,
    name: "Xərçəng",
    startDate: [6, 21],
    endDate: [7, 22],
    element: "Su",
    planet: "Ay",
    positive: "Şəfqətli, Sədaqətli, Yaradıcı",
    negative: "Həddindən artıq həssas, Emosional",
    compatibility: "Balıqlar, Əqrəb",
    love: "Ailə həyatı və emosional bağlılıq onun üçün əsasdır.",
    career: "Psixologiya, tibb, memarlıq.",
    icon: "♋",
    image: "https://freesvg.org/storage/img/thumb/GoldenCancer.png",
    description:"Bürclər üç fərqli keyfiyyətə görə qruplaşdırılır: kardinal (pioner), dəyişkən və sabit bürclər. Xərçəng dörd əsas əlamətdən biridir. Bu əlamətlər mövsümləri başlayır. Qoç, yaz; Xərçəng, yazı; Tərəzi, payız; Oğlaq qışa başlayır. Bu əlamətlər orijinal olmağı sevir və etdikləri hər şeydə birinci olmaq istəyirlər. Onlar cari təyinedicilərdir; dost dairələrində partiya və təşkilatlara təşəbbüs göstərirlər.Xərçəng də Əqrəb və Balıq kimi su elementinə bağlıdır. Bürcün ilk su əlaməti olduğundan, duyğular dənizinin və yaradıcı suların axmasına imkan verən çay kimidir. Xərçəng insanlar ətrafdakı hər kəsin xoşbəxt olmasını istəyirlər. Xərçəng planetar dövrünün təsiri altında olanda, ailəmiz və sevdiklərimizlə vaxt keçirməyə ehtiyac hiss edirik."
  },
  {
    id: 5,
    name: "Şir",
    startDate: [7, 23],
    endDate: [8, 22],
    element: "Atəş",
    planet: "Günəş",
    positive: "Generoz, Yaradıcı, Optimist",
    negative: "Özünü bəyənmiş, Avtoritar",
    compatibility: "Qoç, Oxatan",
    love: "Ehtiraslı, partnyorundan diqqət və heyranlıq gözləyir.",
    career: "Şou-biznes, rəhbərlik, incəsənət.",
    icon: "♌",
    image: "https://freesvg.org/img/GoldenLeo.png",
    description:"Bürclər üç fərqli keyfiyyətə görə qruplaşdırılır: kardinal (pioner), dəyişkən və sabit bürclər. Şir dörd sabit bürcdən biridir; Digər dörd sabit bürclər Buğa, Əqrəb və Dolçadır. Bu bürclər hər mövsümün ortasına düşür. Bunlar tarazlıq əlamətləridir; Onlar özlərinə məqsəd qoyurlar və sonra tikintiyə başlayırlar. Onlar pioner işarələrinin irəli atdığı maraqlı ideyaları götürür və onları hiss olunan bir şeyə çevirir.Şir atəş elementinin idarə etdiyi üç bürcdən biridir (digər ikisi Qoç və Oxatandır). Şir bürcün ikinci od əlaməti olduğundan, Aslanın istiliyi bir qığılcımı hər kəsin hiss edə biləcəyi böyük bir atəşə çevirir. Bir çox Şir bürcü sənətkar və lider olaraq doğulur. Şir bürcü planetar dövranın təsiri altında olanda hamımız diqqət mərkəzində olmaq istəyirik. Eyni zamanda, insanların damarlarını sıxan, həddən artıq tələbkar, rəislik edərək insanları dəli edən insanlara çevrilə bilərik.Atəş elementi ilə əlaqəli olan Şir mehriban və həyat doludur; həmişə gülümsəməyə və yaxşı vaxt keçirməyə çalışır. Ən çətin problemləri belə həll edə bilən zəkaya malik olan Şir bürcü bir çox mürəkkəb vəziyyətlərin həllində asanlıqla təşəbbüskarlıq edir. Günəş tərəfindən idarə olunan, kainatımızın mərkəzində dayanan Şirlər özünü dərk etməyə çalışır və onların eqosu daim böyüyür (Günəş həm də eqo və kişi enerjisini təmsil edir). "
  },
  {
    id: 6,
    name: "Qız",
    startDate: [8, 23],
    endDate: [9, 22],
    element: "Torpaq",
    planet: "Merkuri",
    positive: "Məsuliyyətli, İntizamlı, Ağıllı",
    negative: "Tənqidçi, Həssas",
    compatibility: "Oğlaq, Buğa",
    love: "Sadiq və etibarlı, amma bəzən utancaqdır.",
    career: "Elm, tibb, təhsil.",
    icon: "♍",
    image: "https://freesvg.org/storage/img/thumb/GoldenVirgo.png",
    description:"Bürclər üç fərqli keyfiyyətə görə qruplaşdırılır: kardinal (pioner), dəyişkən və sabit bürclər. Qız dörd dəyişkən bürcdən biridir (digərləri Əkizlər, Oxatan və Balıqlardır). Dəyişən əlamətlər fəsilləri bitirən əlamətlərdir və onlar hər fəsildən dərs almışlar. Onlar bilirlər ki, hər şeyin sonu var və onların missiyası hamının fəsillərin dəyişməsinə uyğunlaşmasına kömək etməkdir. Onlar digər bürclərdən daha müdrikdirlər. Onlar digər bürclərə nisbətən dəyişməyə daha asan uyğunlaşa bilirlər; bir çox vəziyyətə uyğunlaşmaq üçün buqələmun kimi rəngini dəyişirlər. Onlar həm də Bürcün düzəldiciləridir: Kardinallar plan irəli sürür, sabitlər planı həyata keçirir, dəyişənlər isə tənqidi baxışla son nöqtələri qoyurlar.Qız bürcü yer elementinin idarə etdiyi üç bürcdən biridir. Digər yer əlamətləri Buğa və Oğlaqdır. Qız Bürcün ikinci yer bürcü olduğundan, Buğa Buğanın qaldığı yerdən davam edir və mükəmməl bir tikinti planı quraraq Buğa bürcünün möhkəm təməllərini sürətlə qurur. Qız bürcü planetar dövrü ərzində biz tez bir zamanda ilahi olanı təfərrüatlarda müəyyənləşdiririk, düym-düym tam plan hazırlayır və hədəflərimizi yerinə yetiririk. Qız bürcü enerjisi bizi yeni bir iş rejimini sınamağa və ya o günə qədər qəbul etdiyimiz sistemi yeniləməyə təşviq edir. Bu, həm də insanları gələcəklə bağlı narahat edə bilər (və ya hətta narahat edə bilər). Qız bürcünün planetar keçidləri zamanı “nə olarsa” ilişib qala bilərik."
  },
  {
    id: 7,
    name: "Tərəzi",
    startDate: [9, 23],
    endDate: [10, 22],
    element: "Hava",
    planet: "Venera",
    positive: "Ədalətli, Cazibədar, Mehriban",
    negative: "Qərarsız, Qarşıdurmadan qaçan",
    compatibility: "Əkizlər, Dolça",
    love: "Romantik, balanslı münasibətlərə üstünlük verir.",
    career: "Diplomatiya, moda, incəsənət.",
    icon: "♎",
    image: "https://freesvg.org/storage/img/thumb/GoldenLibra.png",
    description:"Bürclər üç fərqli keyfiyyətə görə qruplaşdırılır: kardinal (pioner), dəyişkən və sabit bürclər. Tərəzi dörd əsas bürcdən biridir. Bu əlamətlər mövsümləri başlayır. Qoç, yaz; Xərçəng, yazı; Tərəzi, payız; Oğlaq qışa başlayır. Bu əlamətlər orijinal olmağı sevir və etdikləri hər şeydə birinci olmaq istəyirlər. Onlar cari təyinedicilərdir; dost dairələrində partiya və təşkilatlara təşəbbüs göstərirlər.Tərəzi hava elementinin idarə etdiyi üç bürcdən biridir. Digərləri Əkizlər və Dolçadır. Tərəzi ikinci hava bürcü olduğundan, Əkizlər bürcünün başlatdığı ünsiyyət küləklərini xeyirxahlıq, etiket və ictimai əlaqə küləklərinə çevirir. Lakin Tərəzi bürcünün küləkləri fırtınalı deyil; dəyişiklik küləklərini o qədər yumşaq və yumşaq bir şəkildə gətirir ki, başqa bir məqama çatdığınızı çətinliklə dərk edirsiniz. Hava elementinin mahiyyəti ünsiyyət və zəkadır; İdeyaların yayılmasına kömək edir. Tərəzi bürcünün şəxsiyyətlərarası anlayışı da buna əlavə olunduqda öhdəliklər, faydalı dialoqlar, uğurlu əlaqələr ortaya çıxır. Tərəzi planetinin keçidi zamanı təkbaşına edə bilməyəcəyimiz işləri yerinə yetirmək üçün özümüzə tərəfdaş axtara bilərik. İdarə etdiyi bürclərə kəskin zəka verən hava elementi ilə idarə olunan Tərəzilər yaxşı kitabları, bitməyən müzakirələri və danışacaqları çox insanları sevir. Tərəzi bürcünün hakim planeti olan Venera bu bürcdən olan insanları böyük sevərlər etsə də, digər tərəfdən onları bahalı, dəyərli şeylərə həvəsləndirir."
  },
  {
    id: 8,
    name: "Əqrəb",
    startDate: [10, 23],
    endDate: [11, 21],
    element: "Su",
    planet: "Pluton və Mars",
    positive: "İradəli, Dərin düşüncəli",
    negative: "Həddindən artıq qısqanc, Manipulyativ",
    compatibility: "Balıqlar, Xərçəng",
    love: "Gözlənilməz, amma dərin emosional bağlar yaradır.",
    career: "Elmi tədqiqat, tibb, detektivlik.",
    icon: "♏",
    image: "https://freesvg.org/storage/img/thumb/GoldenScorpio.png",
    description:"Bürclər üç fərqli keyfiyyətə görə qruplaşdırılır: kardinal (pioner), dəyişkən və sabit bürclər. Əqrəb dörd sabit bürcdən biridir; Digər dörd sabit bürclər Buğa, Şir və Dolçadır. Bu bürclər hər mövsümün ortasına düşür. Bunlar tarazlıq əlamətləridir; Onlar özlərinə məqsəd qoyurlar və sonra tikintiyə başlayırlar. Onlar pioner işarələrinin irəli atdığı maraqlı ideyaları götürür və onları hiss olunan bir şeyə çevirir.Əqrəb üç su bürcündən biridir (digərləri Xərçəng və Balıqlardır). Əqrəb Bürcün ikinci su əlamətidir. Onun işi özünün və başqalarının hisslərini gücləndirmək və əbədiləşdirməkdir. Digər su bürcləri kimi Əqrəb də emosiyaları yaşamaq və ifadə etmək üçün yaşayır, lakin duyğulara böyük əhəmiyyət versə də onu kənardan göstərməməsi ilə digər su qruplarından fərqlənir. Əqrəbin bir çox sirləri var və həmişə sirlərini başqalarından gizlədərək yaşayırlar.Əqrəb bürcü ehtiraslı və iddialı insanlardır. Həqiqəti öyrənənə qədər araşdırmaq onun ən görkəmli xüsusiyyətlərindən biridir. Onlar qətiyyətli və qətiyyətlidirlər. Hər zaman həqiqətin fərqində olan və xəyaldan çox hədəflərə diqqət yetirən Əqrəblər kainatın qaydalarını çox yaxşı bilirlər. Bu səbəbdən, başqaları tərəfindən çox vaxt sərt və şiddətli görünürlər, lakin bu realist münasibət onlara təbii olaraq fərqlənməyə imkan verən liderlik xüsusiyyəti verir."
  },
  {
    id: 9,
    name: "Oxatan",
    startDate: [11, 22],
    endDate: [12, 21],
    element: "Atəş",
    planet: "Yupiter",
    positive: "Açıq fikirli, Enerjili",
    negative: "Hədsiz optimist, Sabit olmayan",
    compatibility: "Qoç, Şir",
    love: "Azadlıq və macəra dolu münasibətləri sevir.",
    career: "Səyahət, təlim, tədqiqat.",
    icon: "♐",
    image: "https://freesvg.org/storage/img/thumb/GoldenSagittarius.png",
    description:"Bürclər üç fərqli keyfiyyətə görə qruplaşdırılır: kardinal (pioner), dəyişkən və sabit bürclər. Oxatan dörd dəyişkən bürcdən biridir (digərləri Əkizlər, Qız və Balıqlardır). Dəyişən əlamətlər fəsilləri bitirən əlamətlərdir və onlar hər fəsildən dərs almışlar. Onlar bilirlər ki, hər şeyin sonu var və onların missiyası hamının fəsillərin dəyişməsinə uyğunlaşmasına kömək etməkdir. Onlar digər bürclərdən daha müdrikdirlər. Onlar digər bürclərə nisbətən dəyişməyə daha asan uyğunlaşa bilirlər; bir çox vəziyyətə uyğunlaşmaq üçün buqələmun kimi rəngini dəyişirlər. Onlar həm də Bürcün düzəldiciləridir: Kardinallar plan irəli sürür, sabitlər planı həyata keçirir, dəyişənlər isə tənqidi baxışla son nöqtələri qoyurlar.Oxatan od elementinin idarə etdiyi üç bürcdən biridir (digər iki od əlaməti Qoç və Şir bürcüdür). Oxatan üçüncü və sonuncu atəş bürcü olduğundan, Qoç və Şir bürcünün yaratdığı liderlik atəşindən istifadə edir və onu bilik və fəaliyyətin universal fövqəlnovasına çevirir. Bürcün ən ruhlandırıcı və optimist əlaməti olan Oxatan bizi problemləri həll etməyə və qeyri-məhdud imkanlar ardınca getməyə məcbur edir. Oxatan planetinin keçidi zamanı biz səyahət etməyə, öyrənməyə, mədəniyyətlər arasında əlaqə yaratmağa və üfüqlərimizi genişləndirməyə hazır ola bilərik. Digər yanğın əlamətləri kimi, Oxatan da dünya ilə daim təmasda olmalıdır.Oxatan bürcünün hakim planeti Günəş sistemimizin ən böyük planeti olan Yupiterdir. Buna görə də, bu bürcün insanları “həyatın özündən böyük” ola bilər. Yupiter planetlər arasında qaz nəhənglərindən biri olduğu kimi, özünə güvənən Oxatan enerjisi bəzən hava qazı ilə dolu görünə bilər. Düşünmədən bir şeyin üzərinə tullanmaq Oxatan bürcü adətlərindən biridir. Xoşbəxtlikdən, Yupiter şans gətirir və ayaqlarımızı yerdə möhkəm saxlayır. Oxatanlar hər şeyin ən böyüyünü və ən yaxşısını istəyirlər; O qədər ki, hərdən bunu aşsınlar. Sərhədsiz hedonizm və özünə inam, Oxatan enerjisini pis enerjiyə çevirə bilər."
  },
  {
    id: 10,
    name: "Oğlaq",
    startDate: [12, 22],
    endDate: [1, 19],
    element: "Torpaq",
    planet: "Saturn",
    positive: "Qətiyyətli, İntizamlı",
    negative: "Rasionallıqdan uzaq, Sərt",
    compatibility: "Buğa, Qız",
    love: "Ciddi və uzunmüddətli münasibətləri seçir.",
    career: "İş dünyası, mühəndislik, hüquq.",
    icon: "♑",
    image: "https://freesvg.org/storage/img/thumb/GoldenCapricorn.png",
    description:"Bürclər üç fərqli keyfiyyətə görə qruplaşdırılır: kardinal (pioner), dəyişkən və sabit bürclər. Xərçəng dörd əsas əlamətdən biridir. Bu əlamətlər mövsümləri başlayır. Qoç, yaz; Xərçəng, yazı; Tərəzi, payız; Oğlaq qışa başlayır. Bu əlamətlər orijinal olmağı sevir və etdikləri hər şeydə birinci olmaq istəyirlər. Onlar cari təyinedicilərdir; dost dairələrində partiya və təşkilatlara təşəbbüs göstərirlər.Oğlaq yer elementi ilə əlaqəli üç Bürc bürcündən biridir (digərləri Buğa və Qızdır). Oğlaq üçüncü və son yer işarəsi olduğundan, Buğa bürcünün qaya kimi möhkəm təməlləri Qız bürcünün dahiyanə planlarını möhtəşəm bir binaya, dünyanı idarə edə biləcəkləri bir yerə çevirir. Oğlaqlar Bürcün usta strateqləridir, həmişə beş-on illik planları var. Oğlaq bürcünün planetar dövranının təsiri altında olanda biz ən böyük məqsədlərimizə çatmaq və həyatımızda uzunömürlü strukturlar qurmağa həvəsli oluruq.Oğlaqlar təkcə maddi dünyaya diqqət yetirmirlər, ondan istifadə etməyi də bacarırlar. Təəssüf ki, yer elementi də onları sərt və bəzən inadkar edir; o qədər ki, münasibətə başqa prizmadan baxmağı bacarmırlar. Öz şəxsiyyətlərindən çox fərqli olan insanlar fərqliliklərini qəbul etməkdə çətinlik çəkirlər və öz ənənəvi dəyərlərini tətbiq etməyə cəhd edə bilərlər."
  },
  {
    id: 11,
    name: "Dolça",
    startDate: [1, 20],
    endDate: [2, 18],
    element: "Hava",
    planet: "Uran və Saturn",
    positive: "Orijinal, Dostcanlı",
    negative: "Soyuq, Inadkar",
    compatibility: "Əkizlər, Tərəzi",
    love: "Dərin emosional bağlardan çox intellektual uyğunluq axtarır.",
    career: "Texnologiya, icadlar, ictimai işlər.",
    icon: "♒",
    image: "https://freesvg.org/storage/img/thumb/GoldenAquarius.png",
    description:"Bürclər üç fərqli keyfiyyətə görə qruplaşdırılır: kardinal (pioner), dəyişkən və sabit bürclər. Dolça dörd sabit bürcdən biridir; Digər dörd sabit bürclər Buğa, Şir və Əqrəbdir. Bu bürclər hər mövsümün ortasına düşür. Bunlar tarazlıq əlamətləridir; Onlar özlərinə məqsəd qoyurlar və sonra tikintiyə başlayırlar. Onlar pioner işarələrinin irəli atdığı maraqlı ideyaları götürür və onları hiss olunan bir şeyə çevirir.Bürcün üçüncü hava bürcü olan Dolça, digər hava bürcləri Əkizlər və Tərəzi kimi çox zehnidir. Zehni stimul olmasa, onlar sıxılır və motivasiyaları aşağı düşür. Dolça üçüncü hava bürcü olduğu üçün Əkizlərin sevinc küləklərini və Tərəzi bürcünün sevgi kəpənəyini hər kəs üçün insani əhval-ruhiyyəyə çevirir.Dolçalar utancaq və sakit, əksinə ekssentrik və enerjili ola bilərlər. Bununla belə, onlar istənilən vəziyyətdə başqalarına kömək etməyi sevirlər və hadisələri qərəzsiz qiymətləndirə bilirlər. Bu, onları problemləri asanlıqla həll edə bilən insanlar edir. Dolçalar onları əhatə edən enerjilərə və izdihamlara asanlıqla uyğunlaşa bilsələr də, nadir hallarda tək qalmaq ehtiyacı hiss edirlər. Dolçalar dünyaya imkanlarla dolu bir yer kimi baxır."
  },
  {
    id: 12,
    name: "Balıqlar",
    startDate: [2, 19],
    endDate: [3, 20],
    element: "Su",
    planet: "Neptun və Yupiter",
    positive: "Empatik, Yaradıcı",
    negative: "Həddindən artıq həssas, Qaçqın",
    compatibility: "Xərçəng , Əqrəb",
    love: "Romantik və emosional bağlılıq onun üçün əsasdır.",
    career: "İncəsənət, musiqi, psixologiya.",
    icon: "♓",
    image: "https://freesvg.org/storage/img/thumb/GoldenPisces.png",
    description:"Bürclər üç fərqli keyfiyyətə görə qruplaşdırılır: kardinal (pioner), dəyişkən və sabit bürclər. Balıqlar dörd dəyişkən bürcdən biridir (digərləri Əkizlər, Oxatan və Qızdır). Dəyişən əlamətlər fəsilləri bitirən əlamətlərdir və onlar hər fəsildən dərs almışlar. Onlar bilirlər ki, hər şeyin sonu var və onların missiyası hamının fəsillərin dəyişməsinə uyğunlaşmasına kömək etməkdir. Onlar digər bürclərdən daha müdrikdirlər. Onlar digər bürclərə nisbətən dəyişməyə daha asan uyğunlaşa bilirlər; bir çox vəziyyətə uyğunlaşmaq üçün buqələmun kimi rəngini dəyişirlər. Onlar həm də Bürcün düzəldiciləridir: Kardinallar plan irəli sürür, sabitlər planı hərəkətə gətirir, dəyişənlər isə tənqidi baxışla son nöqtələri qoyurlar.Balıqlar su elementi ilə əlaqəli üç Bürc bürcündən biridir (digərləri Xərçəng və Əqrəbdir). Balıqlar üçüncü və sonuncu su bürcü olduğundan, Xərçəngin emosional dalğalarını və Əqrəbin təzyiqli sularını duyğular okeanına tökür. Balıqlar enerjisi aktivləşəndə ​​dərinə dalmağa hazır olun; Balıqların enerjisi şəfqətimizi oyadır, əziyyət çəkən insanlara ürəyimizi açmağa imkan verir. Balıq bürcünün planetar dövrü ərzində bu enerjidən xəbərdar olub-olmamağımızdan asılı olmayaraq ətrafımızdakı insanlarla intuitiv əlaqə qura bilərik. Biz özümüzü yaradıcı yollarla da ifadə edə bilərik: musiqi, film, təsviri incəsənət və rəqs; bütün bunlar Balıqların ixtisasıdır."
  },
];

export default zodiacData;
  